#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/pcs-remote-monitoring-webui"

# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# The version is stored in a file, to avoid hardcoding it in multiple places
APP_VERSION=$(cat "$APP_HOME/version")

build_docker_image() {
    check_dependency_docker

    cd $APP_HOME

    rm -fR out/docker

    mkdir -p            out/docker/src/
    mkdir -p            out/docker/public/

    cp -pR package.json out/docker/
    cp -pR src/*        out/docker/src/
    cp -pR public/*     out/docker/public/

    cp scripts/docker/.dockerignore              out/docker/
    cp scripts/docker/Dockerfile                 out/docker/
    cp scripts/docker/run.sh                     out/docker/
    cp scripts/docker/nginx.conf                 out/docker/

    cd out/docker/
    docker build --tag "$DOCKER_IMAGE:$APP_VERSION" --squash --compress --label "Tags=azure,iot,pcs,webui,react" .
}

# compile
build_docker_image

set +e
