// flyout
export const FLYOUT_SHOW = 'FLYOUT_SHOW';
export const FLYOUT_HIDE = 'FLYOUT_HIDE';

// message
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS';
export const LOAD_MESSAGE_FAILED = 'LOAD_MESSAGE_FAILED';

// device
export const LOAD_DEVICES_SUCCESS = 'LOAD_DEVICES_SUCCESS';
export const LOAD_DEVICES_FAILED = 'LOAD_DEVICES_FAILED';
export const LOAD_DEVICES_GROUP_SUCCESS = 'LOAD_DEVICES_GROUP_SUCCESS';

// map
export const LOAD_MAPKEY_SUCCESS = 'LOAD_MAPKEY_SUCCESS';
export const LOAD_MAPKEY_FAILED = 'LOAD_MAPKEY_FAILED';

// telemetry
export const SELECT_TELEMETRY_TYPE = 'SELECT_TELEMETRY_TYPE';
export const LOAD_TELEMETRY_TYPES_SUCCESS = 'LOAD_TELEMETRY_TYPES_SUCCESS';
export const LOAD_TELEMETRY_TYPES_FAILED = 'LOAD_TELEMETRY_TYPES_FAILED';
export const LOAD_TELEMETRY_MESSAGES_SUCCESS =
  'LOAD_TELEMETRY_MESSAGES_SUCCESS';
export const UPDATE_TELEMETRY_TYPES_SUCCESS = 'UPDATE_TELEMETRY_TYPES_SUCCESS';

// ajax
export const AJAX_SUCCESS = 'AJAX_SUCCESS';
export const AJAX_FAILED = 'AJAX_FAILED';

// filter
export const LOAD_DEVICE_GROUPS_SUCCESS = 'LOAD_DEVICE_GROUPS_SUCCESS';
export const DEVICE_GROUP_CHANGED = 'DEVICE_GROUP_CHANGED';

// kpi
export const LOAD_ALARMLIST_SUCCESS = 'LOAD_ALARMLIST_SUCCESS';
