// flyout
export const FLYOUT_SHOW = 'FLYOUT_SHOW';
export const FLYOUT_HIDE = 'FLYOUT_HIDE';

// message
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS';
export const LOAD_MESSAGE_FAILED = 'LOAD_MESSAGE_FAILED';

// device
export const LOAD_DEVICES_SUCCESS = 'LOAD_DEVICES_SUCCESS';
export const LOAD_DEVICES_FAILED = 'LOAD_DEVICES_FAILED';

// LOAD_MAPKEY_SUCCESS
export const LOAD_MAPKEY_SUCCESS = 'LOAD_MAPKEY_SUCCESS';
export const LOAD_MAPKEY_FAILED = 'LOAD_MAPKEY_FAILED';
