// Copyright (c) Microsoft. All rights reserved.

// flyout
export const FLYOUT_SHOW = 'FLYOUT_SHOW';
export const FLYOUT_HIDE = 'FLYOUT_HIDE';

// message
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS';
export const LOAD_MESSAGE_FAILED = 'LOAD_MESSAGE_FAILED';

// device
export const LOAD_DEVICES_SUCCESS = 'LOAD_DEVICES_SUCCESS';
export const LOAD_DEVICES_FAILED = 'LOAD_DEVICES_FAILED';
export const LOAD_DEVICES_GROUP_SUCCESS = 'LOAD_DEVICES_GROUP_SUCCESS';
export const LOAD_DEVICE_TELEMETRY_SUCCESS = 'LOAD_DEVICE_TELEMETRY_SUCCESS';

// map
export const LOAD_MAPKEY_SUCCESS = 'LOAD_MAPKEY_SUCCESS';
export const LOAD_MAPKEY_FAILED = 'LOAD_MAPKEY_FAILED';

export const MANAGE_FILTERS_FLYOUT_SAVE_SUCCESS = 'MANAGE_FILTERS_FLYOUT_SAVE_SUCCESS';

export const MANAGE_FILTERS_FLYOUT_UPDATE_SUCCESS = 'MANAGE_FILTERS_FLYOUT_UPDATE_SUCCESS';

export const MANAGE_FILTERS_FLYOUT_DELETE_SUCCESS = 'MANAGE_FILTERS_FLYOUT_DELETE_SUCCESS';

export const MANAGE_FILTERS_FLYOUT_SAVE_FAILED = 'MANAGE_FILTERS_FLYOUT_SAVE_FAILED';

// telemetry
export const SELECT_TELEMETRY_TYPE = 'SELECT_TELEMETRY_TYPE';
export const LOAD_TELEMETRY_TYPES_SUCCESS = 'LOAD_TELEMETRY_TYPES_SUCCESS';
export const LOAD_TELEMETRY_TYPES_FAILED = 'LOAD_TELEMETRY_TYPES_FAILED';
export const LOAD_TELEMETRY_MESSAGES_SUCCESS = 'LOAD_TELEMETRY_MESSAGES_SUCCESS';
export const UPDATE_TELEMETRY_TYPES_SUCCESS = 'UPDATE_TELEMETRY_TYPES_SUCCESS';

// ajax
export const AJAX_SUCCESS = 'AJAX_SUCCESS';
export const AJAX_FAILED = 'AJAX_FAILED';

export const KPI_WIDGET_INTERVAL_CHANGE = 'KPI_WIDGET_INTERVAL_CHANGE';
export const KPI_REFRESH_CHART_DATA_START = 'KPI_REFRESH_CHART_DATA_START';
// filter
export const LOAD_DEVICE_GROUPS_SUCCESS = 'LOAD_DEVICE_GROUPS_SUCCESS';
export const DEVICE_GROUP_CHANGED = 'DEVICE_GROUP_CHANGED';
export const LOAD_FIELDS_SUCCESS = 'LOAD_FIELDS_SUCCESS';

// kpi
export const REFRESH_ALL_CHART_DATA_SUCCESS = 'REFRESH_ALL_CHART_DATA_SUCCESS';

//Device tag flyout
export const SHOW_DEVICE_TAG_FLYOUT = 'SHOW_DEVICE_TAG_FLYOUT';

//Device List actions
export const DEVICE_LIST_ROW_SELECTION_CHANGED = 'DEVICE_LIST_ROW_SELECTION_CHANGED';
export const DEVICE_LIST_COMMON_TAGS_VALUE_CHANGED = 'DEVICE_LIST_COMMON_TAGS_VALUE_CHANGED';
export const DEVICE_LIST_COMMON_TAGS_VALUE_CHANGED_SUCCESS = 'DEVICE_LIST_COMMON_TAGS_VALUE_CHANGED_SUCCESS';

//Rule list actions
export const RULE_LIST_ROW_SELECTION_CHANGED = 'RULE_LIST_ROW_SELECTION_CHANGED';