#!/usr/bin/env bash
set -e

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

check_dependency_npm

# Treat warnings as errors because
export CI=true

npm test

## broken? "flow" is not recognized
# npm flow
