const lang = {
  REGIONDETAILS: {
    REGION: 'Region',
    DEVICES: 'DEVICES',
    ALARMS: 'Alarms',
    WARNINGS: 'Warnings',
    TOTAL: 'Total',
    ONLINE: 'Online',
    OFFLINE: 'Offline'
  },
  DASHBOARD: {
    DEVICELOCATION: 'Device Location',
    MORE: 'MORE',
    AZUREPROJECTNAME: 'Azure Iot Suite Remote Monitoring',
    DASHBOARD: 'Dashboard',
    CONTOSO: 'Contoso'
  },
  TELEMETRY: {
    OK: 'ok'
  },
  DEVICES: {
    CAUTION: 'Caution: You are scheduling an action that will effect {0} devices.',
    DEVICEID: 'DeviceId',
    TYPE: 'Type',
    FIRMWAREVERSION: 'Firmware Version',
    MANUFACTURER: 'Manufacturer',
    MODELNUMBER: 'Model Number',
    STATE: 'State',
    SYNC: 'Sync',
    ENABLED: 'Enabled',
    CONNECTED: 'Connected',
    DISCONNECTED: 'Diconnected',
    DEVICEDETAIL: 'Device Detail',
    ACTONDEVICES: 'Act on devices',
    CHOOSEDEVICES: 'Choose devices',
    NEWGROUP: '(new group)',
    ADDDEVICES: 'Add Devices',
    PROVISIONDEVICES: 'Provision devices',
    MANUAL: 'Manual',
    AUTOMATIC: 'Automatic',
    SELECTMETHOD: 'Select your provisioning method',
    CREATEDEVICE: 'Create device',
    DEVICETYPES: 'Device Types',
    SELECTTYPE: 'Select an existing device type',
    AUTHENTICATIONTYPE: 'Authentication type',
    SYMMETRICKEY: 'Symmetric Key',
    X509: 'X.509',
    PRIMARYKEY: 'Primary Key',
    SECONDARYKEY: 'Secondary Key',
    AUTOGENERATEKEYS: 'Auto Generate Keys',
    PRIMARYTHUMBPRINT: 'Primary thumbprint',
    SENCONDARYTHUMBPRINT: 'Secondary thumbprint',
    SIMULATEDDEVICES: 'Simulated devices(s)',
    NUMBEROFDEVICES: 'Number of devices',
    NEWDEVICEID: 'Device ID',
    GENERATEDEVICEID: 'Generate an ID for me',
    DPSTENANT: 'DPS Tenant',
    NEWTENANT: 'New Tenant',
    ENROLLMENT: 'Enrollment',
    INDIVIDUAL: 'Individual',
    GROUP: 'Group',
    GROUPNAME: 'Group Name',
    SECURESTORAGETYPE: 'Secure storage type',
    RELEVANTSTORAGEINFO: 'Relevant storage info',
    DEVICECONFIGURATION: 'Device configuration',
    DEVICEORGANIZATION: 'Device organization',
    DEVICENUMBER: 'Number of devices',
    PROPERTYNAME: 'Name',
    PROPERTYTYPE: 'Type',
    PROPERTYVALUE: 'Value',
    TASKNAME: 'Task Name',
    CONFIGPROPERTIES: 'Config Properties (properties.desired.config.*)',
    CONFIRM: 'Confirm',
    AVAILABLEACTIONS: 'Available actions',
    SELECTTIMELINE: 'Select timeline',
    NOW: 'Now',
    TIMEWINDOW: 'Time window',
    ADD: 'Add',
    DELETE: 'Remove',
    CHANGEDEVICECONFIG: 'Change device configuration',
    ORGANIZEMYDEVICE: 'Organize my devices',
    SCHEDULEANACTION: 'Schedule an action',
    CHANGEPROPERTYX: 'ChangepropertyX',
    LASTACTIVITYTIME: 'Last activity time',
    LASTSTATUSUPDATEDTIME: 'Last status updated time'
  },
  LEFTNAV: {
    DASHBOARD: 'Dashboard',
    DEVICES: 'Devices',
    RULES_ACTIONS: 'Rules & Actions',
    MAINTENANCE: 'Maintenance'
  }
};
export default lang;
